### ISSUE TITLE
Houdini 18.5 pcache python error

### ISSUE THREAD

**Issue by oktomus** [Unity-Technologies/VFXToolbox#28]
There is an error when trying to export a set of points using pcache node in Houdini 18.

```
Python error: Traceback (most recent call last):
File "<stdin>", line 30, in <module>
File "Sop/pcache, PythonModule", line 303, in saveAsFile
TypeError: 'newline' is an invalid keyword argument for this function
```

I can try updating the code but it seems the hda plugin code is not open source.

Bug reproduction steps: https://www.youtube.com/watch?v=z1Am4DIDEzw

**Comment by sourya-sen** [comment]
Same issue here.

**Comment by sourya-sen** [comment]
@oktomus if you checkout to commit c84601a, pcache node seems to work. It's the latest python3 commit that has broken that node but the older version seems to still work fine.

**Comment by peeweek** [comment]
I've upgraded the python exporters to they are now compatible with python 3. As for now, we will assume python3 to be the default for all the houdini exporters in VFXToolbox

**Comment by oktomus** [comment]
Thank you!

**Comment by Swweeessf** [comment]
This error is trying again/ 
 i reinstall houdini and vfxtollbox, but all this doesnt work again.
